// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jafuyqfmcpilcvzzmmwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZnV5cWZtY3BpbGN2enptbXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzQ1MjgsImV4cCI6MjA2Mzg1MDUyOH0.BV-eT4ZYXFfuN6sxt1qQ_CSZ5hAaUB-8pPEZyARAOg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);